// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type League struct {
	ID               string       `json:"id"`
	UserID           string       `json:"user_id"`
	Platform         string       `json:"platform"`
	ExternalLeagueID string       `json:"external_league_id"`
	Name             string       `json:"name"`
	Season           string       `json:"season"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type Session struct {
	Token     string       `json:"token"`
	UserID    string       `json:"user_id"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	PasswordHash  string         `json:"password_hash"`
	SleeperUserID sql.NullString `json:"sleeper_user_id"`
	EspnSwid      sql.NullString `json:"espn_swid"`
	EspnS2        sql.NullString `json:"espn_s2"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}
