// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateLeague(ctx context.Context, arg CreateLeagueParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteLeague(ctx context.Context, id string) error
	GetLeaguesByUser(ctx context.Context, userID string) ([]League, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
}

var _ Querier = (*Queries)(nil)
