// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createLeague = `-- name: CreateLeague :exec
INSERT INTO leagues (id, user_id, platform, external_league_id, name, season)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateLeagueParams struct {
	ID               string `json:"id"`
	UserID           string `json:"user_id"`
	Platform         string `json:"platform"`
	ExternalLeagueID string `json:"external_league_id"`
	Name             string `json:"name"`
	Season           string `json:"season"`
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) error {
	_, err := q.db.ExecContext(ctx, createLeague,
		arg.ID,
		arg.UserID,
		arg.Platform,
		arg.ExternalLeagueID,
		arg.Name,
		arg.Season,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, sleeper_user_id, espn_swid, espn_s2)
VALUES (?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID            string         `json:"id"`
	Username      string         `json:"username"`
	SleeperUserID sql.NullString `json:"sleeper_user_id"`
	EspnSwid      sql.NullString `json:"espn_swid"`
	EspnS2        sql.NullString `json:"espn_s2"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.SleeperUserID,
		arg.EspnSwid,
		arg.EspnS2,
	)
	return err
}

const deleteLeague = `-- name: DeleteLeague :exec
DELETE FROM leagues
WHERE id = ?
`

func (q *Queries) DeleteLeague(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteLeague, id)
	return err
}

const getLeaguesByUser = `-- name: GetLeaguesByUser :many
SELECT id, user_id, platform, external_league_id, name, season, craeted_at FROM leagues
WHERE user_id = ?
ORDER BY name ASC
`

func (q *Queries) GetLeaguesByUser(ctx context.Context, userID string) ([]League, error) {
	rows, err := q.db.QueryContext(ctx, getLeaguesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []League
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.ExternalLeagueID,
			&i.Name,
			&i.Season,
			&i.CraetedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, username, sleeper_user_id, espn_swid, espn_s2, craeted_at FROM users
WHERE id = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SleeperUserID,
		&i.EspnSwid,
		&i.EspnS2,
		&i.CraetedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, sleeper_user_id, espn_swid, espn_s2, craeted_at FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.SleeperUserID,
		&i.EspnSwid,
		&i.EspnS2,
		&i.CraetedAt,
	)
	return i, err
}
